version: '3.4'

services:
  customers:
    image: radusumall/ecommerceapicustomers
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  orders:
    image: radusumall/ecommerceapiorders
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  products:
    image: radusumall/ecommerceapiproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  search:
    image: radusumall/ecommerceapisearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://localhost:19081/lil/products/
      - Services__Customers=http://localhost:19081/lil/customers/
      - Services__Orders=http://localhost:19081/lil/orders/
    ports:
      - "6004:80"

